name: lunar-e2e-pin-rotation-e25bab5b3
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened e25bab5b3'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-e25bab5b3'
    runs-on: localdev-e2e-test-37431937787-1-github-3-e2e
    steps:
      - run: /bin/echo 'pin rotation CI e25bab5b3'
